extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/*.bril'
timeout = 50

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.ssa]
pipeline = [
    "bril2json",
    "python3 ../05/to_ssa.py",
    "brili -p {args}",
]

[runs.licm]
pipeline = [
    "bril2json",
    "python3 ../05/to_ssa.py",
    "python3 ./licm.py",
    "brili -p {args}"
]
