extract = 'total_dyn_inst: (\d+)'
benchmarks = '../../bril/benchmarks/*.bril'
timeout = 50

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.lvndce]
pipeline = [
    "bril2json",
    "python3 ../03/lvn.py",
    "python3 ../03/dce.py",
    "brili -p {args}",
]

[runs.specop]
pipeline = [
    "bril2json",
    "bash -c 'tee >(brili -t {args} > /dev/null; cat)'",
    "python3 ./specop.py",
    "python3 ../03/lvn.py",
    "python3 ../03/dce.py",
    "brili -p {args}",
]
